config/routes.rb
Rails.application.routes.draw do
  resources :appartenances
  resources :books
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appartenance.rb
class Appartenance < ApplicationRecord
  belongs_to :book
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :appartenance

  validates :title, presence: true
  validates :description, presence: true
  validates :picture, presence: true
  validates :amazon_url, presence: true
  validates :author, presence: true
  validates :language, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/appartenances_controller.rb
class AppartenancesController < ApplicationController
  before_action :set_appartenance, only: [:show, :edit, :update, :destroy]

  # GET /appartenances
  # GET /appartenances.json
  def index
    @appartenances = Appartenance.all
  end

  # GET /appartenances/1
  # GET /appartenances/1.json
  def show
  end

  # GET /appartenances/new
  def new
    @appartenance = Appartenance.new
  end

  # GET /appartenances/1/edit
  def edit
  end

  # POST /appartenances
  # POST /appartenances.json
  def create
    @appartenance = Appartenance.new(appartenance_params)

    respond_to do |format|
      if @appartenance.save
        format.html { redirect_to @appartenance, notice: 'Appartenance was successfully created.' }
        format.json { render :show, status: :created, location: @appartenance }
      else
        format.html { render :new }
        format.json { render json: @appartenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appartenances/1
  # PATCH/PUT /appartenances/1.json
  def update
    respond_to do |format|
      if @appartenance.update(appartenance_params)
        format.html { redirect_to @appartenance, notice: 'Appartenance was successfully updated.' }
        format.json { render :show, status: :ok, location: @appartenance }
      else
        format.html { render :edit }
        format.json { render json: @appartenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appartenances/1
  # DELETE /appartenances/1.json
  def destroy
    @appartenance.destroy
    respond_to do |format|
      format.html { redirect_to appartenances_url, notice: 'Appartenance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appartenance
      @appartenance = Appartenance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appartenance_params
      params.fetch(:appartenance, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :picture, :amazon_url, :author, :language, :category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appartenances/_form.html.erb
<%= simple_form_for(@appartenance) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :book, as: :check_boxes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appartenances/edit.html.erb
<h1>Editing Appartenance</h1>

<%= render 'form', appartenance: @appartenance %>

<%= link_to 'Show', @appartenance %> |
<%= link_to 'Back', appartenances_path %>

app/views/appartenances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appartenances</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appartenances.each do |appartenance| %>
      <tr>
        <td><%= link_to 'Show', appartenance %></td>
        <td><%= link_to 'Edit', edit_appartenance_path(appartenance) %></td>
        <td><%= link_to 'Destroy', appartenance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appartenance', new_appartenance_path %>

app/views/appartenances/new.html.erb
<h1>New Appartenance</h1>

<%= render 'form', appartenance: @appartenance %>

<%= link_to 'Back', appartenances_path %>

app/views/appartenances/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_appartenance_path(@appartenance) %> |
<%= link_to 'Back', appartenances_path %>

app/views/books/_form.html.erb
<div class="container">
  <%= simple_form_for(@book) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :author %>
      <%= f.input :category %>
      <%= f.input :picture %>
      <%= f.input :amazon_url %>
      <%= f.input :language %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1>Modifiez le livre :</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= book.category %></td>
        <td><%= book.picture %></td>
        <td><%= book.amazon_url %></td>
        <td><%= book.language %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @book.picture %>
</p>

<p>
  <strong>Amazon:</strong>
  <%= @book.amazon_url %>
</p>

<p>
  <strong>Amazon:</strong>
  <%= @book.language %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
<br>
<a href="#">Créer une appartenance</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibliotech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello bienvenue sur Bibliotech</h1>

<h2>Mettre son entreprise en avant</h2>
<h2>Partager le savoir !</h2>
<h2>Ne pas gaspiller d'argent</h2>
<h2>Ecologique</h2>


<p><a href="/books">Voir les livres</a></p>

<p>Je créer ma bibliotech</p>
<p>Rechercher un livre</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>